[env:m5stack-atoms3]
platform = espressif32@6.7.0
board = m5stack-atoms3
framework = arduino
monitor_speed = 1500000
board_build.arduino.memory_type = qio_opi
lib_deps =
  m5stack/M5Unified @ ^0.2.8
  bblanchon/ArduinoJson @ ^7
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM